## Competition02 Bank
### 1. コンペ概要 
銀行の顧客情報をもとに、定期預金キャンペーンに反応するかどうかを予測する分類問題である。  
顧客の年齢や職業、婚姻状況、過去のキャンペーン結果などの情報から、定期預金を申し込むかどうかを予測する。

### 2. 目的  
- EDAを行い、データの特徴を理解する 
- 適切な前処理や特徴量作成を行い、機械学習モデルを作成して予測精度の向上を目指す  
- Titanicで学んだ分析の流れを自分で考えながら実践する

### 3. 使用ライブラリ  
- pandas  
- numpy  
- matplotlib  
- scikit-learn

### 4. データ読み込み

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
train = pd.read_csv("../data/train.csv")
train.head()

,id,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,1,39,blue-collar,married,secondary,no,1756,yes,no,cellular,3,apr,939,1,-1,0,unknown,1
1,2,51,entrepreneur,married,primary,no,1443,no,no,cellular,18,feb,172,10,-1,0,unknown,1
2,3,36,management,single,tertiary,no,436,no,no,cellular,13,apr,567,1,595,2,failure,1
3,4,63,retired,married,secondary,no,474,no,no,cellular,25,jan,423,1,-1,0,unknown,1
4,5,31,management,single,tertiary,no,354,no,no,cellular,30,apr,502,1,9,2,success,1

- age 年齢  
- job 職種  
- marital 未婚/既婚  
- education 教育水準  
- default 債務不履行かあるか(yes,no)  
- balance 年間平均残高(€)  
- housing 住宅ローン(yes,no)  
- loan 個人ローン(yes,no)  
- contact 連絡方法  
- day 最終接触日  
- month 最終接触月  
- duration 最終接触時間(秒)  
- compaign 現キャンペーンにおける接触回数
- pdays 経過日数:前キャンペン接触後の日数  
- previous 接触実績:現キャンペーン以前までに顧客に接触した回数  
- poutcome 前回キャンペーンの成果  
- y 定額預金申し込み有無(1:有,0:無)  
  

現キャンペーンが定額預金に関するものでその結果がy

In [4]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 27128 entries, 0 to 27127
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         27128 non-null  int64
 1   age        27128 non-null  int64
 2   job        27128 non-null  str
 3   marital    27128 non-null  str
 4   education  27128 non-null  str
 5   default    27128 non-null  str
 6   balance    27128 non-null  int64
 7   housing    27128 non-null  str
 8   loan       27128 non-null  str
 9   contact    27128 non-null  str
 10  day        27128 non-null  int64
 11  month      27128 non-null  str
 12  duration   27128 non-null  int64
 13  campaign   27128 non-null  int64
 14  pdays      27128 non-null  int64
 15  previous   27128 non-null  int64
 16  poutcome   27128 non-null  str
 17  y          27128 non-null  int64
dtypes: int64(9), str(9)
memory usage: 3.7 MB

In [5]:
train.isnull().sum()

id           0
age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [6]:
train.describe()

,id,age,balance,day,duration,campaign,pdays,previous,y
count,27128.000000,27128.000000,27128.000000,27128.000000,27128.000000,27128.000000,27128.000000,27128.000000,27128.000000
mean,13564.500000,40.951010,1355.800870,15.806215,260.711295,2.751769,40.528052,0.579733,0.117001
std,7831.323388,10.608542,3003.305272,8.337904,260.091727,3.126594,100.382462,2.503653,0.321427
min,1.000000,18.000000,-6847.000000,1.000000,0.000000,1.000000,-1.000000,0.000000,0.000000
25%,6782.750000,33.000000,72.000000,8.000000,104.000000,1.000000,-1.000000,0.000000,0.000000
50%,13564.500000,39.000000,449.000000,16.000000,182.000000,2.000000,-1.000000,0.000000,0.000000
75%,20346.250000,48.000000,1428.000000,21.000000,323.000000,3.000000,-1.000000,0.000000,0.000000
max,27128.000000,95.000000,102127.000000,31.000000,4918.000000,63.000000,871.000000,275.000000,1.000000